[project]
name = "django-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "cookiecutter>=2.6.0",
  "django>=5.2.7",
  "djlint>=1.36.4",
  "ruff>=0.14.1",
]

[dependency-groups]
dev = [
]
